package com.npm.mmdb.mybatis.model;

public class Gid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.id
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.year
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private Short year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.month
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private Byte month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.day
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private Byte day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.away_abbrev
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private String awayAbbrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.away_sport_code
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private String awaySportCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.home_abbrev
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private String homeAbbrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.home_sport_code
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private String homeSportCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.game_number
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private String gameNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid.note
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.id
     *
     * @return the value of gid.id
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.id
     *
     * @param id the value for gid.id
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.year
     *
     * @return the value of gid.year
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.year
     *
     * @param year the value for gid.year
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setYear(Short year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.month
     *
     * @return the value of gid.month
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public Byte getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.month
     *
     * @param month the value for gid.month
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setMonth(Byte month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.day
     *
     * @return the value of gid.day
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public Byte getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.day
     *
     * @param day the value for gid.day
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setDay(Byte day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.away_abbrev
     *
     * @return the value of gid.away_abbrev
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public String getAwayAbbrev() {
        return awayAbbrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.away_abbrev
     *
     * @param awayAbbrev the value for gid.away_abbrev
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setAwayAbbrev(String awayAbbrev) {
        this.awayAbbrev = awayAbbrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.away_sport_code
     *
     * @return the value of gid.away_sport_code
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public String getAwaySportCode() {
        return awaySportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.away_sport_code
     *
     * @param awaySportCode the value for gid.away_sport_code
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setAwaySportCode(String awaySportCode) {
        this.awaySportCode = awaySportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.home_abbrev
     *
     * @return the value of gid.home_abbrev
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public String getHomeAbbrev() {
        return homeAbbrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.home_abbrev
     *
     * @param homeAbbrev the value for gid.home_abbrev
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setHomeAbbrev(String homeAbbrev) {
        this.homeAbbrev = homeAbbrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.home_sport_code
     *
     * @return the value of gid.home_sport_code
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public String getHomeSportCode() {
        return homeSportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.home_sport_code
     *
     * @param homeSportCode the value for gid.home_sport_code
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setHomeSportCode(String homeSportCode) {
        this.homeSportCode = homeSportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.game_number
     *
     * @return the value of gid.game_number
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public String getGameNumber() {
        return gameNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.game_number
     *
     * @param gameNumber the value for gid.game_number
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setGameNumber(String gameNumber) {
        this.gameNumber = gameNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid.note
     *
     * @return the value of gid.note
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid.note
     *
     * @param note the value for gid.note
     *
     * @mbggenerated Thu Oct 09 08:33:48 EDT 2014
     */
    public void setNote(String note) {
        this.note = note;
    }
}