package com.npm.mmdb.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class GidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public GidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Short value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Short value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Short value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Short value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Short value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Short value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Short> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Short> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Short value1, Short value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Short value1, Short value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(Byte value) {
            addCriterion("month =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(Byte value) {
            addCriterion("month <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(Byte value) {
            addCriterion("month >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(Byte value) {
            addCriterion("month >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(Byte value) {
            addCriterion("month <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(Byte value) {
            addCriterion("month <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<Byte> values) {
            addCriterion("month in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<Byte> values) {
            addCriterion("month not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(Byte value1, Byte value2) {
            addCriterion("month between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(Byte value1, Byte value2) {
            addCriterion("month not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andDayIsNull() {
            addCriterion("day is null");
            return (Criteria) this;
        }

        public Criteria andDayIsNotNull() {
            addCriterion("day is not null");
            return (Criteria) this;
        }

        public Criteria andDayEqualTo(Byte value) {
            addCriterion("day =", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotEqualTo(Byte value) {
            addCriterion("day <>", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThan(Byte value) {
            addCriterion("day >", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThanOrEqualTo(Byte value) {
            addCriterion("day >=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThan(Byte value) {
            addCriterion("day <", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThanOrEqualTo(Byte value) {
            addCriterion("day <=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayIn(List<Byte> values) {
            addCriterion("day in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotIn(List<Byte> values) {
            addCriterion("day not in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayBetween(Byte value1, Byte value2) {
            addCriterion("day between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotBetween(Byte value1, Byte value2) {
            addCriterion("day not between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevIsNull() {
            addCriterion("away_abbrev is null");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevIsNotNull() {
            addCriterion("away_abbrev is not null");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevEqualTo(String value) {
            addCriterion("away_abbrev =", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevNotEqualTo(String value) {
            addCriterion("away_abbrev <>", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevGreaterThan(String value) {
            addCriterion("away_abbrev >", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevGreaterThanOrEqualTo(String value) {
            addCriterion("away_abbrev >=", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevLessThan(String value) {
            addCriterion("away_abbrev <", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevLessThanOrEqualTo(String value) {
            addCriterion("away_abbrev <=", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevLike(String value) {
            addCriterion("away_abbrev like", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevNotLike(String value) {
            addCriterion("away_abbrev not like", value, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevIn(List<String> values) {
            addCriterion("away_abbrev in", values, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevNotIn(List<String> values) {
            addCriterion("away_abbrev not in", values, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevBetween(String value1, String value2) {
            addCriterion("away_abbrev between", value1, value2, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwayAbbrevNotBetween(String value1, String value2) {
            addCriterion("away_abbrev not between", value1, value2, "awayAbbrev");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeIsNull() {
            addCriterion("away_sport_code is null");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeIsNotNull() {
            addCriterion("away_sport_code is not null");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeEqualTo(String value) {
            addCriterion("away_sport_code =", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeNotEqualTo(String value) {
            addCriterion("away_sport_code <>", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeGreaterThan(String value) {
            addCriterion("away_sport_code >", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeGreaterThanOrEqualTo(String value) {
            addCriterion("away_sport_code >=", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeLessThan(String value) {
            addCriterion("away_sport_code <", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeLessThanOrEqualTo(String value) {
            addCriterion("away_sport_code <=", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeLike(String value) {
            addCriterion("away_sport_code like", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeNotLike(String value) {
            addCriterion("away_sport_code not like", value, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeIn(List<String> values) {
            addCriterion("away_sport_code in", values, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeNotIn(List<String> values) {
            addCriterion("away_sport_code not in", values, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeBetween(String value1, String value2) {
            addCriterion("away_sport_code between", value1, value2, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andAwaySportCodeNotBetween(String value1, String value2) {
            addCriterion("away_sport_code not between", value1, value2, "awaySportCode");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevIsNull() {
            addCriterion("home_abbrev is null");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevIsNotNull() {
            addCriterion("home_abbrev is not null");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevEqualTo(String value) {
            addCriterion("home_abbrev =", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevNotEqualTo(String value) {
            addCriterion("home_abbrev <>", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevGreaterThan(String value) {
            addCriterion("home_abbrev >", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevGreaterThanOrEqualTo(String value) {
            addCriterion("home_abbrev >=", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevLessThan(String value) {
            addCriterion("home_abbrev <", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevLessThanOrEqualTo(String value) {
            addCriterion("home_abbrev <=", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevLike(String value) {
            addCriterion("home_abbrev like", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevNotLike(String value) {
            addCriterion("home_abbrev not like", value, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevIn(List<String> values) {
            addCriterion("home_abbrev in", values, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevNotIn(List<String> values) {
            addCriterion("home_abbrev not in", values, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevBetween(String value1, String value2) {
            addCriterion("home_abbrev between", value1, value2, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeAbbrevNotBetween(String value1, String value2) {
            addCriterion("home_abbrev not between", value1, value2, "homeAbbrev");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeIsNull() {
            addCriterion("home_sport_code is null");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeIsNotNull() {
            addCriterion("home_sport_code is not null");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeEqualTo(String value) {
            addCriterion("home_sport_code =", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeNotEqualTo(String value) {
            addCriterion("home_sport_code <>", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeGreaterThan(String value) {
            addCriterion("home_sport_code >", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeGreaterThanOrEqualTo(String value) {
            addCriterion("home_sport_code >=", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeLessThan(String value) {
            addCriterion("home_sport_code <", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeLessThanOrEqualTo(String value) {
            addCriterion("home_sport_code <=", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeLike(String value) {
            addCriterion("home_sport_code like", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeNotLike(String value) {
            addCriterion("home_sport_code not like", value, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeIn(List<String> values) {
            addCriterion("home_sport_code in", values, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeNotIn(List<String> values) {
            addCriterion("home_sport_code not in", values, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeBetween(String value1, String value2) {
            addCriterion("home_sport_code between", value1, value2, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andHomeSportCodeNotBetween(String value1, String value2) {
            addCriterion("home_sport_code not between", value1, value2, "homeSportCode");
            return (Criteria) this;
        }

        public Criteria andGameNumberIsNull() {
            addCriterion("game_number is null");
            return (Criteria) this;
        }

        public Criteria andGameNumberIsNotNull() {
            addCriterion("game_number is not null");
            return (Criteria) this;
        }

        public Criteria andGameNumberEqualTo(String value) {
            addCriterion("game_number =", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberNotEqualTo(String value) {
            addCriterion("game_number <>", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberGreaterThan(String value) {
            addCriterion("game_number >", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberGreaterThanOrEqualTo(String value) {
            addCriterion("game_number >=", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberLessThan(String value) {
            addCriterion("game_number <", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberLessThanOrEqualTo(String value) {
            addCriterion("game_number <=", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberLike(String value) {
            addCriterion("game_number like", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberNotLike(String value) {
            addCriterion("game_number not like", value, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberIn(List<String> values) {
            addCriterion("game_number in", values, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberNotIn(List<String> values) {
            addCriterion("game_number not in", values, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberBetween(String value1, String value2) {
            addCriterion("game_number between", value1, value2, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andGameNumberNotBetween(String value1, String value2) {
            addCriterion("game_number not between", value1, value2, "gameNumber");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gid
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 09 11:54:30 EDT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}