package com.npm.mmdb.mybatis.model;

public class GidFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid_file.id
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid_file.filename
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid_file.ext
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid_file.local_path
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    private String localPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gid_file.id_gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    private Integer idGid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid_file.id
     *
     * @return the value of gid_file.id
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid_file.id
     *
     * @param id the value for gid_file.id
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid_file.filename
     *
     * @return the value of gid_file.filename
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid_file.filename
     *
     * @param filename the value for gid_file.filename
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid_file.ext
     *
     * @return the value of gid_file.ext
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid_file.ext
     *
     * @param ext the value for gid_file.ext
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void setExt(String ext) {
        this.ext = ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid_file.local_path
     *
     * @return the value of gid_file.local_path
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public String getLocalPath() {
        return localPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid_file.local_path
     *
     * @param localPath the value for gid_file.local_path
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gid_file.id_gid
     *
     * @return the value of gid_file.id_gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public Integer getIdGid() {
        return idGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gid_file.id_gid
     *
     * @param idGid the value for gid_file.id_gid
     *
     * @mbggenerated Thu Oct 09 11:54:30 EDT 2014
     */
    public void setIdGid(Integer idGid) {
        this.idGid = idGid;
    }
}