package com.npm.mmdb.mybatis.dao;

import com.npm.mmdb.mybatis.model.GidFile;
import com.npm.mmdb.mybatis.model.GidFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GidFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int countByExample(GidFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int deleteByExample(GidFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int insert(GidFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int insertSelective(GidFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    List<GidFile> selectByExample(GidFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    GidFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int updateByExampleSelective(@Param("record") GidFile record, @Param("example") GidFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int updateByExample(@Param("record") GidFile record, @Param("example") GidFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int updateByPrimaryKeySelective(GidFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gid_file
     *
     * @mbggenerated Thu Oct 09 08:43:23 EDT 2014
     */
    int updateByPrimaryKey(GidFile record);
}