package com.npm.mmdb.mybatis.dao.gid;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.npm.mmdb.mybatis.dao.RootDao;
import com.npm.mmdb.mybatis.model.gid.Gid;
import com.npm.mmdb.mybatis.model.gid.GidExample;


public interface GidMapper extends RootDao<Gid, Integer, GidExample>
{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int countByExample(GidExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int deleteByExample(GidExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int insert(Gid record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int insertSelective(Gid record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	List<Gid> selectByExample(GidExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	Gid selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int updateByExampleSelective(@Param("record") Gid record, @Param("example") GidExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int updateByExample(@Param("record") Gid record, @Param("example") GidExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int updateByPrimaryKeySelective(Gid record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	int updateByPrimaryKey(Gid record);
}