package com.npm.mmdb.mybatis.model.gid;

import com.npm.mmdb.mybatis.model.RootModel;

public class Gid extends RootModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.id
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private Integer	id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.year
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private Integer	year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.month
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private Integer	month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.day
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private Integer	day;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.away_abbrev
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	awayAbbrev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.away_sport_code
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	awaySportCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.home_abbrev
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	homeAbbrev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.home_sport_code
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	homeSportCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.game_number
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	gameNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.note
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	note;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public Gid(Integer id, Integer year, Integer month, Integer day, String awayAbbrev, String awaySportCode,
			String homeAbbrev, String homeSportCode, String gameNumber, String note)
	{
		this.id = id;
		this.year = year;
		this.month = month;
		this.day = day;
		this.awayAbbrev = awayAbbrev;
		this.awaySportCode = awaySportCode;
		this.homeAbbrev = homeAbbrev;
		this.homeSportCode = homeSportCode;
		this.gameNumber = gameNumber;
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.id
	 * @return  the value of gid.id
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public Integer getId( )
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.year
	 * @return  the value of gid.year
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public Integer getYear( )
	{
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.month
	 * @return  the value of gid.month
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public Integer getMonth( )
	{
		return month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.day
	 * @return  the value of gid.day
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public Integer getDay( )
	{
		return day;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.away_abbrev
	 * @return  the value of gid.away_abbrev
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getAwayAbbrev( )
	{
		return awayAbbrev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.away_sport_code
	 * @return  the value of gid.away_sport_code
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getAwaySportCode( )
	{
		return awaySportCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.home_abbrev
	 * @return  the value of gid.home_abbrev
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getHomeAbbrev( )
	{
		return homeAbbrev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.home_sport_code
	 * @return  the value of gid.home_sport_code
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getHomeSportCode( )
	{
		return homeSportCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.game_number
	 * @return  the value of gid.game_number
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getGameNumber( )
	{
		return gameNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid.note
	 * @return  the value of gid.note
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getNote( )
	{
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	public String toString( )
	{
		StringBuilder sb = new StringBuilder( );
		sb.append(getClass( ).getSimpleName( ));
		sb.append(" [");
		sb.append("Hash = ").append(hashCode( ));
		sb.append(", id=").append(id);
		sb.append(", year=").append(year);
		sb.append(", month=").append(month);
		sb.append(", day=").append(day);
		sb.append(", awayAbbrev=").append(awayAbbrev);
		sb.append(", awaySportCode=").append(awaySportCode);
		sb.append(", homeAbbrev=").append(homeAbbrev);
		sb.append(", homeSportCode=").append(homeSportCode);
		sb.append(", gameNumber=").append(gameNumber);
		sb.append(", note=").append(note);
		sb.append("]");
		return sb.toString( );
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public static class GidBuilder
	{
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.id
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private Integer	id;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.year
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private Integer	year;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.month
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private Integer	month;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.day
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private Integer	day;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.away_abbrev
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	awayAbbrev;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.away_sport_code
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	awaySportCode;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.home_abbrev
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	homeAbbrev;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.home_sport_code
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	homeSportCode;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.game_number
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	gameNumber;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid.note
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	note;
		
		public GidBuilder id(Integer val)
		{
			id = val;
			return this;
		}
		
		public GidBuilder year(Integer val)
		{
			year = val;
			return this;
		}
		
		public GidBuilder month(Integer val)
		{
			month = val;
			return this;
		}
		
		public GidBuilder day(Integer val)
		{
			day = val;
			return this;
		}
		
		public GidBuilder awayAbbrev(String val)
		{
			awayAbbrev = val;
			return this;
		}
		
		public GidBuilder awaySportCode(String val)
		{
			awaySportCode = val;
			return this;
		}
		
		public GidBuilder homeAbbrev(String val)
		{
			homeAbbrev = val;
			return this;
		}
		
		public GidBuilder homeSportCode(String val)
		{
			homeSportCode = val;
			return this;
		}
		
		public GidBuilder gameNumber(String val)
		{
			gameNumber = val;
			return this;
		}
		
		public GidBuilder note(String val)
		{
			note = val;
			return this;
		}
		
		public Gid build( )
		{
			return new Gid(id, year, month, day, awayAbbrev, awaySportCode, homeAbbrev, homeSportCode, gameNumber, note);
		}
	}
}