package com.npm.mmdb.mybatis.model.gid;

import com.npm.mmdb.mybatis.model.RootModel;

public class GidFile extends RootModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.id
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private Integer	id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.filename
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.ext
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	ext;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.local_path
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private String	localPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.id_gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	private Integer	idGid;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid_file
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public GidFile(Integer id, String filename, String ext, String localPath, Integer idGid)
	{
		this.id = id;
		this.filename = filename;
		this.ext = ext;
		this.localPath = localPath;
		this.idGid = idGid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid_file.id
	 * @return  the value of gid_file.id
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public Integer getId( )
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid_file.filename
	 * @return  the value of gid_file.filename
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getFilename( )
	{
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid_file.ext
	 * @return  the value of gid_file.ext
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getExt( )
	{
		return ext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid_file.local_path
	 * @return  the value of gid_file.local_path
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public String getLocalPath( )
	{
		return localPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gid_file.id_gid
	 * @return  the value of gid_file.id_gid
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public Integer getIdGid( )
	{
		return idGid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gid_file
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	@Override
	public String toString( )
	{
		StringBuilder sb = new StringBuilder( );
		sb.append(getClass( ).getSimpleName( ));
		sb.append(" [");
		sb.append("Hash = ").append(hashCode( ));
		sb.append(", id=").append(id);
		sb.append(", filename=").append(filename);
		sb.append(", ext=").append(ext);
		sb.append(", localPath=").append(localPath);
		sb.append(", idGid=").append(idGid);
		sb.append("]");
		return sb.toString( );
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table gid_file
	 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
	 */
	public static class GidFileBuilder
	{
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.id
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private Integer	id;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.filename
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	filename;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.ext
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	ext;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.local_path
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private String	localPath;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column gid_file.id_gid
		 * @mbggenerated  Mon Oct 13 19:19:57 EDT 2014
		 */
		private Integer	idGid;
		
		public GidFileBuilder id(Integer val)
		{
			id = val;
			return this;
		}
		
		public GidFileBuilder filename(String val)
		{
			filename = val;
			return this;
		}
		
		public GidFileBuilder ext(String val)
		{
			ext = val;
			return this;
		}
		
		public GidFileBuilder localPath(String val)
		{
			localPath = val;
			return this;
		}
		
		public GidFileBuilder idGid(Integer val)
		{
			idGid = val;
			return this;
		}
		
		public GidFile build( )
		{
			return new GidFile(id, filename, ext, localPath, idGid);
		}
	}
}